# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install global tsx for running TypeScript
RUN npm install -g tsx

WORKDIR /app

# Copy MCP server files
COPY mcp-server/package.json mcp-server/tsconfig.json mcp-server/index.ts ./

# Install dependencies
RUN npm install --production

# Expose stdin/stdout for MCP
# Start MCP server
CMD ["tsx", "index.ts"]
